#!/bin/bash

# +--------+
# | System |
# +--------+

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias suspend='sudo pm-suspend'

alias open=xdg-open
alias bigf= 'find / -xdev -type f -size +500M'  # display "big" files > 500M

# +-----+
# | X11 |
# +-----+

alias xpropc='xprop | grep WM_CLASS' # display xprop class

# +-----+
# | Zsh |
# +-----+

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index # directory stack
alias zshc="vi ~/.zshrc"
alias zshs="source ~/.zshrc"

# +----+
# | ls |
# +----+

alias ls='ls --color=auto'
alias lsl='ls -l'
alias ll='ls -lahF'
alias lls='ls -lahFtr'
alias la='ls -A'
alias l='ls -CF'

# +----+
# | ls |
# +----+

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'

# +----+
# | cp |
# +----+

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'
alias la='ls -alh'

# +------+
# | grep |
# +------+

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# +------+
# | ping |
# +------+

alias pg='ping 8.8.8.8'

# +----+
# | bc |
# +----+

alias bc="bc -q"

# +-----+
# | bat |
# +-----+

alias batl='bat --paging=never -l log'

# +--------+
# | pacman |
# +--------+

alias paci='sudo pacman -S'               # install
alias pachi='sudo pacman -Ql'             # Pacman Has Installed - what files where installed in a package
alias pacs='sudo pacman -Ss'              # search
alias pacu='sudo pacman -Syu'             # update
alias pacr='sudo pacman -R'               # remove package but not dependencies
alias pacrr='sudo pacman -Rs'             # remove package with unused dependencies by other softwares
alias pacrc='sudo pacman -Sc'             # remove pacman's cache
alias pacro='pacman -Rns $(pacman -Qtdq)'
alias pacrl='rm /var/lib/pacman/db.lck'   # pacman remove locks
alias pacls="sudo pacman -Qe"
alias pacc='sudo pacman -Sc'
alias paccc='sudo pacman -Scc'            # empty the whole cache

# +-----+
# | yay |
# +-----+

alias yayi='yay -S'     # install
alias yayhi='yay -Ql'   # Yay Has Installed - what files where installed in a package
alias yays='yay -Ss'    # search
alias yayu='yay -Syu'   # update
alias yayr='yay -R'     # remove package but not dependencies
alias yayrr='yay -Rs'   # remove package with unused dependencies by other softwares
alias yayrc='yay -Sc'   # remove yay's cache
alias yayls="yay -Qe"

# +--------+
# | netctl |
# +--------+

alias wifi='sudo wifi-menu -o'


# +------+
# | Hugo |
# +------+

alias hugostart="hugo server -DEF --ignoreCache"

# +--------+
# | muffet |
# +--------+

alias deadlink="muffet -t 20"

# +---------+
# | netstat |
# +---------+

alias port="netstat -tulpn | grep"

# +--------+
# | Neovim |
# +--------+

alias vi='nvim'
alias svim='sudoedit'
alias dvim="vim -u /usr/share/nvim/archlinux.vim" # nvim with default config
alias nvimc='rm -I $VIMCONFIG/swap/*'             # clean nvim swap file
alias nvimcu='rm -I $VIMCONFIG/undo/*'            # clean the vim undo
alias nviml='nvim -w $VIMCONFIG/vimlog "$@"'      # log the keystrokes

# git
alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'                                                                           # display remote branch
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
alias gclean="git branch --merged | grep  -v '\\*\\|master\\|main\\|develop' | xargs -n 1 git branch -d" # Delete local branch merged with master
alias gblog="git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'"                                                              # git log for each branches
alias gsub="git submodule update --remote"                                                        # pull submodules
alias gexport="git diff-tree -r --no-commit-id --name-only --diff-filter=ACMRT $1 | tar -czf $2.tgz -T -"

# +------+
# | tmux |
# +------+

alias tmuxk='tmux kill-session -t'
alias tmuxa='tmux attach -t'
alias tmuxl='tmux list-sessions'
alias tmuxc="vi ~/.tmux.conf"
alias tmuxs="tmux source ~/.tmux.conf"
alias tmuxr="tmux-session restore && tmuxa 0"

# +-------+
# | tmuxp |
# +-------+

alias mux='tmuxp load'

# +---------+
# | lazygit |
# +---------+

alias lg='lazygit'

# +--------+
# | docker |
# +--------+

# alias docki="docker inspect"                                                    # display the information about a container
# alias docke='docker exec -t -i'                                                 # going inside a container
# alias dockDE='docker rm $(docker ps -a -q) && docker rmi $(docker images -q)'   # delete every containers / images
# alias dockstats='docker stats $(docker ps -q)'                                  # stats on images
# alias dockls='docker ps'                                                        # list docker containers
# alias dockimg='docker images'                                                   # list images installed
# alias dockprune='docker system prune -a'                                        # prune everything
# alias dockceu='docker-compose run --rm -u $(id -u):$(id -g)'                    # run as the host user
# alias dockce='docker-compose run --rm'

# +----------------+
# | docker-compose |
# +----------------+

# alias docker-compose-dev='docker-compose -f docker-compose-dev.yml' # run a different config file than the default one

# +----------+
# | Personal |
# +----------+

# Folders
alias work="$HOME/code"
alias doc="$HOME/Documents"
alias dow="$HOME/Downloads"
alias dot="$HOME/dotfiles"

# Mindmaps
# alias freebrain="freemind $CLOUD/knowledge_base/_BRAINSTORMING/*.mm &"
# alias freelists="freemind $CLOUD/knowledge_base/_LISTS/*.mm &"
# alias freepain="freemind $CLOUD/knowledge_base/_PROBLEMS/*.mm &"

# +--------+
# | Golang |
# +--------+
# alias gosrc="$GOPATH/src/" # golang src
# alias gobin="$GOPATH/bin/" # golang bin
# alias gob="go build"
# alias gor="go run"
# alias goc="go clean -i"
# alias gta="go test ./..."       # go test all
# alias gia="go install ./..."    # go install all

# Clojure
# alias cljrepl='clojure -Sdeps "{:deps {com.bhauman/rebel-readline {:mvn/version \"0.1.4\"}}}" -m rebel-readline.main'


# +--------+
# | Server |
# +--------+

# My server
alias live='ssh root@45.76.158.60'
alias tserver='ssh -i ~/code/keys/NewCashSystem.pem ec2-user@ec2-18-163-114-233.ap-east-1.compute.amazonaws.com'
alias utserver='ssh -i ~/code/keys/movies.pem admin@18.136.131.54'
alias trsup='scp -i ~/code/keys/NewCashSystem.pem -r /mnt/d/Work/new-cash-system/client/build/* ec2-user@ec2-18-163-114-233.ap-east-1.compute.amazonaws.com:/srv/live_cash_pro/'

# +--------+
# | Qrcode |
# +--------+

qrcodeFunction() {
  $HOME/.config/qrcode/qc.py $1
  /usr/bin/xdg-open "$HOME/qrcode.png"
}
alias qrcode='qrcodeFunction'

# +---------+
# | Laravel |
# +---------+

alias art="php artisan"

## Useful aliases
alias grubup="sudo update-grub"
alias fixpacman="sudo rm /var/lib/pacman/db.lck"
alias tarnow='tar -acf '
alias untar='tar -zxvf '
alias wget='wget -c '
alias rmpkg="sudo pacman -Rdd"
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias hw='hwinfo --short'                                   # Hardware Info
alias big="expac -H M '%m\t%n' | sort -h | nl"              # Sort installed packages according to size in MB (expac must be installed)
alias gitpkg='pacman -Q | grep -i "\-git" | wc -l'			# List amount of -git packages

# Get fastest mirrors 
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" 
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist" 
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist" 
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist" 

